###
# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

### Test Upload PDF
POST http://localhost:8000/upload-pdf
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="Apple_KI.pdf"

< /Users/ericbernet/Desktop/01_Studium/01_HDM/01_Vorlesungen/07_Semester/Cloud/Apple_KI.pdf
--WebAppBoundary--

